# Generated by Django 4.2.2 on 2025-10-07 05:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.JSONField(blank=True, default=dict, verbose_name='label')),
                ('creator_id', models.UUIDField(default=uuid.uuid4, editable=False, null=True, verbose_name='creator_id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('tenant_id', models.UUIDField(default='00000000-0000-0000-0000-000000000001', verbose_name='tenant_id')),
                ('name', models.CharField(default='', max_length=50, verbose_name='name')),
                ('alias', models.CharField(default='', max_length=50, verbose_name='alias')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email')),
                ('phone', models.CharField(default='', max_length=50, verbose_name='phone')),
                ('is_active', models.BooleanField(default=True, verbose_name='is_active')),
                ('type', models.CharField(choices=[('admin', 'admin'), ('workflow_admin', 'workflow_admin'), ('normal', 'normal')], max_length=50, verbose_name='type')),
                ('avatar', models.CharField(default='', max_length=500, verbose_name='avatar')),
                ('lang', models.CharField(choices=[('zh-cn', 'Simple Chinese'), ('en', 'English')], default='zh-cn', max_length=100, verbose_name='lang')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.JSONField(blank=True, default=dict, verbose_name='label')),
                ('creator_id', models.UUIDField(default=uuid.uuid4, editable=False, null=True, verbose_name='creator_id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('tenant_id', models.UUIDField(default='00000000-0000-0000-0000-000000000001', verbose_name='tenant_id')),
                ('name', models.CharField(default='', max_length=50, verbose_name='name')),
                ('description', models.CharField(default='', max_length=200, verbose_name='description')),
                ('token', models.CharField(default='', help_text='token, generated by server', max_length=50, verbose_name='token')),
                ('type', models.CharField(choices=[('admin', 'admin'), ('workflow_admin', 'workflow_admin')], default='admin', max_length=50, verbose_name='type')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Dept',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.JSONField(blank=True, default=dict, verbose_name='label')),
                ('creator_id', models.UUIDField(default=uuid.uuid4, editable=False, null=True, verbose_name='creator_id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('name', models.CharField(default='', help_text='department name', max_length=50, verbose_name='name')),
                ('leader', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='dept_leader', to=settings.AUTH_USER_MODEL)),
                ('parent_dept', models.ForeignKey(db_constraint=False, default='00000000-0000-0000-0000-000000000000', help_text='default value 00000000-0000-0000-0000-000000000000 means no parent department', on_delete=django.db.models.deletion.DO_NOTHING, to='account.dept')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creator_id', models.UUIDField(default=uuid.uuid4, editable=False, null=True, verbose_name='creator_id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('tenant_id', models.UUIDField(default='00000000-0000-0000-0000-000000000001', verbose_name='tenant_id')),
                ('name', models.CharField(default='', max_length=50, verbose_name='role name')),
                ('description', models.CharField(default='', max_length=200, verbose_name='role description')),
                ('label', models.CharField(blank=True, default='', help_text='label info,you can use set a json data include role info id in your internal system', max_length=50, verbose_name='label')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.JSONField(blank=True, default=dict, verbose_name='label')),
                ('creator_id', models.UUIDField(default=uuid.uuid4, editable=False, null=True, verbose_name='creator_id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('tenant_id', models.UUIDField(default='00000000-0000-0000-0000-000000000001', verbose_name='tenant_id')),
                ('role', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='account.role')),
                ('user', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserDept',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.JSONField(blank=True, default=dict, verbose_name='label')),
                ('creator_id', models.UUIDField(default=uuid.uuid4, editable=False, null=True, verbose_name='creator_id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('tenant_id', models.UUIDField(default='00000000-0000-0000-0000-000000000001', verbose_name='tenant_id')),
                ('is_primary', models.BooleanField(default=True, verbose_name='is_primary')),
                ('dept', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='account.dept')),
                ('user', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.JSONField(blank=True, default=dict, verbose_name='label')),
                ('creator_id', models.UUIDField(default=uuid.uuid4, editable=False, null=True, verbose_name='creator_id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('name', models.CharField(default='', help_text="tenant's name", max_length=100, verbose_name='name')),
                ('domain', models.CharField(default='', help_text='the domain of the tenant, such as xxx.com', max_length=100, verbose_name='domain')),
                ('logo_path', models.CharField(default='', help_text='the logo image of the tenant to be displayed on website, such as logo.jpg', max_length=100, verbose_name='logo_path')),
                ('workflow_limit', models.BigIntegerField(default=0, verbose_name='workflow_limit')),
                ('ticket_limit', models.BigIntegerField(default=0, verbose_name='ticket_limit')),
                ('is_active', models.BooleanField(default=True, verbose_name='is_active')),
                ('parent_tenant', models.ForeignKey(db_constraint=False, default='00000000-0000-0000-0000-000000000000', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='account.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DeptApprover',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.JSONField(blank=True, default=dict, verbose_name='label')),
                ('creator_id', models.UUIDField(default=uuid.uuid4, editable=False, null=True, verbose_name='creator_id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('tenant_id', models.UUIDField(default='00000000-0000-0000-0000-000000000001', verbose_name='tenant_id')),
                ('dept', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='account.dept')),
                ('user', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='dept',
            name='tenant',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='account.tenant'),
        ),
        migrations.AddField(
            model_name='user',
            name='dept',
            field=models.ManyToManyField(through='account.UserDept', to='account.dept'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ManyToManyField(through='account.UserRole', to='account.role'),
        ),
    ]
