# Generated by Django 5.2.12 on 2026-05-02 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_personalaccesstoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalaccesstoken',
            name='user',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='personal_access_tokens', to=settings.AUTH_USER_MODEL),
        ),
    ]
