# Generated by Django 4.2.2 on 2025-10-07 05:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.JSONField(blank=True, default=dict, verbose_name='label')),
                ('creator_id', models.UUIDField(default=uuid.uuid4, editable=False, null=True, verbose_name='creator_id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('model_name', models.CharField(max_length=100, verbose_name='model name')),
                ('data', models.JSONField(verbose_name='archived data')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
