# Generated by Django 5.2.12 on 2026-04-20 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_alter_customfield_field_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfield',
            name='field_type',
            field=models.CharField(choices=[('text', 'text'), ('number', 'number'), ('date', 'date'), ('datetime', 'datetime'), ('time', 'time'), ('select', 'select'), ('cascade', 'cascade'), ('user', 'user'), ('file', 'file'), ('richtext', 'richtext'), ('externaldata', 'externaldata')], max_length=50, verbose_name='field_type'),
        ),
    ]
