# Generated by Django 4.2.2 on 2025-10-07 05:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.JSONField(blank=True, default=dict, verbose_name='label')),
                ('creator_id', models.UUIDField(default=uuid.uuid4, editable=False, null=True, verbose_name='creator_id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('tenant_id', models.UUIDField(default='00000000-0000-0000-0000-000000000001', verbose_name='tenant_id')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.JSONField(blank=True, default=dict, verbose_name='label')),
                ('creator_id', models.UUIDField(default=uuid.uuid4, editable=False, null=True, verbose_name='creator_id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('tenant_id', models.UUIDField(default='00000000-0000-0000-0000-000000000001', verbose_name='tenant_id')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='name')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='description')),
                ('type', models.CharField(blank=True, choices=[('archived', 'archived'), ('default', 'default'), ('candidate', 'candidate')], max_length=50, null=True, verbose_name='type')),
                ('workflow', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='workflow_versions', to='workflow.record')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.JSONField(blank=True, default=dict, verbose_name='label')),
                ('creator_id', models.UUIDField(default=uuid.uuid4, editable=False, null=True, verbose_name='creator_id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('tenant_id', models.UUIDField(default='00000000-0000-0000-0000-000000000001', verbose_name='tenant_id')),
                ('permission', models.CharField(blank=True, choices=[('view', 'view'), ('intervene', 'intervene'), ('admin', 'admin'), ('api', 'api')], max_length=100, null=True, verbose_name='permission')),
                ('target_type', models.CharField(blank=True, choices=[('user', 'user'), ('dept', 'dept'), ('app', 'app')], max_length=100, null=True, verbose_name='target_type')),
                ('target', models.CharField(blank=True, max_length=100, null=True, verbose_name='target')),
                ('version', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='workflow.version')),
                ('workflow', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='workflow.record')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.JSONField(blank=True, default=dict, verbose_name='label')),
                ('creator_id', models.UUIDField(default=uuid.uuid4, editable=False, null=True, verbose_name='creator_id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('tenant_id', models.UUIDField(default='00000000-0000-0000-0000-000000000001', verbose_name='tenant_id')),
                ('channels', models.CharField(blank=True, default='', max_length=500, verbose_name='workflow_notification')),
                ('title_template', models.CharField(blank=True, default='', max_length=200, verbose_name='title_template')),
                ('content_template', models.CharField(default='title:{title}, created at:{created_at}', max_length=1000, verbose_name='content_template')),
                ('version', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='workflow.version')),
                ('workflow', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='workflow.record')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.JSONField(blank=True, default=dict, verbose_name='label')),
                ('creator_id', models.UUIDField(default=uuid.uuid4, editable=False, null=True, verbose_name='creator_id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('tenant_id', models.UUIDField(default='00000000-0000-0000-0000-000000000001', verbose_name='tenant_id')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('type', models.CharField(choices=[('start', 'start'), ('common', 'common'), ('end', 'end'), ('parallel', 'parallel'), ('exclusive', 'exclusive'), ('include_gw', 'include_gw'), ('timer', 'timer')], default='common', max_length=50, verbose_name='type')),
                ('layout', models.JSONField(verbose_name='layout')),
                ('props', models.JSONField(verbose_name='props')),
                ('version', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='workflow.version')),
                ('workflow', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='workflow.record')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Hook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.JSONField(blank=True, default=dict, verbose_name='label')),
                ('creator_id', models.UUIDField(default=uuid.uuid4, editable=False, null=True, verbose_name='creator_id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('tenant_id', models.UUIDField(default='00000000-0000-0000-0000-000000000001', verbose_name='tenant_id')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='permission')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='description')),
                ('url', models.CharField(blank=True, max_length=500, null=True, verbose_name='url')),
                ('token', models.CharField(blank=True, max_length=200, null=True, verbose_name='token')),
                ('events', models.CharField(blank=True, max_length=500, null=True, verbose_name='events')),
                ('version', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='workflow.version')),
                ('workflow', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='workflow.record')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.JSONField(blank=True, default=dict, verbose_name='label')),
                ('creator_id', models.UUIDField(default=uuid.uuid4, editable=False, null=True, verbose_name='creator_id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('tenant_id', models.UUIDField(default='00000000-0000-0000-0000-000000000001', verbose_name='tenant_id')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('type', models.CharField(choices=[('accept', 'accept'), ('reject', 'reject'), ('other', 'other')], verbose_name='type')),
                ('layout', models.JSONField(verbose_name='layout')),
                ('props', models.JSONField(verbose_name='props')),
                ('source_node', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='workflow.node')),
                ('target_node', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transition_destination', to='workflow.node')),
                ('version', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='workflow.version')),
                ('workflow', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transition_workflow', to='workflow.record')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.JSONField(blank=True, default=dict, verbose_name='label')),
                ('creator_id', models.UUIDField(default=uuid.uuid4, editable=False, null=True, verbose_name='creator_id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('tenant_id', models.UUIDField(default='00000000-0000-0000-0000-000000000001', verbose_name='tenant_id')),
                ('type', models.CharField(choices=[('text', 'text'), ('number', 'number'), ('date', 'date'), ('time', 'time'), ('radio', 'radio'), ('checkbox', 'checkbox'), ('select', 'select'), ('cascade', 'cascade'), ('user', 'user'), ('file', 'file'), ('rich_text', 'rich_text'), ('row', 'row'), ('col', 'col')], max_length=50, verbose_name='type')),
                ('component_key', models.CharField(max_length=50, verbose_name='field_key')),
                ('component_name', models.CharField(max_length=50, verbose_name='component_name')),
                ('description', models.CharField(blank=True, default='', max_length=200, verbose_name='description')),
                ('layout', models.JSONField(verbose_name='layout')),
                ('props', models.JSONField(verbose_name='props')),
                ('order_id', models.IntegerField(default=0, verbose_name='order_id')),
                ('parent_component', models.ForeignKey(db_constraint=False, default='0000', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='workflow.component')),
                ('version', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='workflow.version')),
                ('workflow', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='workflow.record')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BasicInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.JSONField(blank=True, default=dict, verbose_name='label')),
                ('creator_id', models.UUIDField(default=uuid.uuid4, editable=False, null=True, verbose_name='creator_id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('tenant_id', models.UUIDField(default='00000000-0000-0000-0000-000000000001', verbose_name='tenant_id')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('description', models.CharField(max_length=200, verbose_name='description')),
                ('version', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='workflow.version')),
                ('workflow', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='basic_info', to='workflow.record')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
