# Generated by Django 5.2.12 on 2026-05-02 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0003_rename_externaldata_component_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='type',
            field=models.CharField(choices=[('text', 'text'), ('number', 'number'), ('date', 'date'), ('time', 'time'), ('radio', 'radio'), ('checkbox', 'checkbox'), ('select', 'select'), ('cascade', 'cascade'), ('user', 'user'), ('file', 'file'), ('richtext', 'richtext'), ('externaldata', 'externaldata'), ('row', 'row'), ('col', 'col')], max_length=50, verbose_name='type'),
        ),
    ]
