blank_issues_enabled: false
contact_links:
  - name: 📖 Documentation
    url: https://popper.js.org/docs/
    about:
      Not sure how to use Popper? Read our documentation to learn everything
      about it.
  - name: ❓ StackOverflow
    url: https://stackoverflow.com/questions/tagged/popper.js
    about: Having troubles with Popper? Ask to the awesome SO community!
  - name: 💬 Discussions
    url: https://github.com/popperjs/popper-core/discussions
    about: Want to talk about Popper with other users? Join us on GitHub Discussions!
