# Generated by Django 4.2.2 on 2025-10-07 05:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.JSONField(blank=True, default=dict, verbose_name='label')),
                ('creator_id', models.UUIDField(default=uuid.uuid4, editable=False, null=True, verbose_name='creator_id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('tenant_id', models.UUIDField(default='00000000-0000-0000-0000-000000000001', verbose_name='tenant_id')),
                ('name', models.CharField(default='', max_length=50, verbose_name='name')),
                ('description', models.CharField(default='', max_length=200, verbose_name='description')),
                ('type', models.CharField(default='', max_length=50, verbose_name='type')),
                ('extra', models.JSONField(max_length=1000, verbose_name='extra')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
