name: Functional Tests
on: [push, pull_request]
env:
  CI: true
  PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true
  PUPPETEER_EXEC_PATH: google-chrome-stable

jobs:
  functional-chromium:
    name: Chromium Functional Tests
    runs-on: ubuntu-latest
    container:
      image: ianwalter/puppeteer:3.0.0
      options: --shm-size=1g
    steps:
      - uses: actions/checkout@v2
      - uses: CultureHQ/actions-yarn@master
        with:
          args: install
      - run: yarn test:functional
        env:
          PUPPETEER_BROWSER: chromium
