name: Build Task Image
on:
  push:
    tags:
      - 'r**'
    branches:
      - v3.0.1
jobs:
  build_task:
    name: Build Task
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: docker_compose_deploy/loonflow-backend/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          # tags: blackholll/loonflow-backend:latest,blackholll/loonflow-backend:${{ github.ref_name }}
          tags: blackholll/loonflow-backend:${{ github.ref_name }}
